frequency: 30

two_d_mode: true

publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

odom0: /mobile_base_controller/odom
odom0_config: [false,  false,  false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]

imu0: /imu
imu0_config: [false,  false,  false,
               false, false, true,
               false, false, false,
               false, false, true,
               true, false, false]
